# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d770992e752abb5dc42fbbaf5eeb8e00051b2fd240d48b0c100263152ca7b07ffa8180c45494aa08876b6e8fe6d0d7898149128726121ed1acad1f60989698de

test:
  secret_key_base: 65de8ce9b1864b4dbcb9ff89ef118557dcfc1406d9333d73167290763cc286ba86509de2bbdeef3a178fdb2f5255b9eb1dc170e9ea24237855a5dc4d5851e75f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
